name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: ./build.sh
        shell: bash
        env:
          BETTERQQNT_VERSION: 0.1.5

      - uses: actions/upload-artifact@v3
        with:
          name: bqqenv-${{ github.sha }}
          path: dist
