name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Package
        run: |
          mkdir build
          cd build
          cmake -G 'Visual Studio 17 2022' ..
          cmake --build . --target bqqenv --config MinSizeRel
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: bqqenv-${{ github.sha }}
          path: build/MinSizeRel/bqqenv.exe
